### PR TITLE
jsdoc improvment + explicit path

### PR DESCRIPTION
**Pull request by jimmywarting**

### CODE REVIEW

**Comment by doowb** [comment]
Thanks for the PR!

I'm curious to know the reasoning behind the `explicit path` changes. Is this due to changes in newer versions of Node.js?

**Comment by jimmywarting** [comment]
> Is this due to changes in newer versions of Node.js?

yea, many are already moving towards esm and it requires a `explicit path`
https://nodejs.org/docs/latest-v17.x/api/esm.html#mandatory-file-extensions

Even doe you are using cjs, having explicit path can make the transition to esm easier if you ever try to refactor to esm at a later stage. 
resolving path remotely via http import just isn't good with index.js and extension-less path, cuz the remote client don't have access to the filesystem, so guessing what you meant becomes hard

**Comment by doowb** [comment]
Thank you for the explanation!

**Comment by jimmywarting** [comment]
Would you be willing to move to esm-only syntax if i sent you a PR?

It would be a breaking change and require node v12.20
cjs can not use require to load it, they would need to use `import('npm-api')` in that case...

**Comment by doowb** [comment]
> Would you be willing to move to esm-only syntax if i sent you a PR?

I'm open to reviewing it...

> cjs can not use require to load it, they would need to use `import('npm-api')`

I had experimented with this before to get a better understanding of which formats work. I'll have to look back at what I tried, but I thought I was able to get both to work for cjs. I won't be able to dig in for a few days (maybe not until the weekend).

**Comment by jimmywarting** [comment]
you are depending on node-fetch after all...
node-fetch@3 went esm-only also, so switching to esm aswell would only benefit you,

**Pull request merged**
