### PR TITLE
Replace request with node-fetch

### LINKED ISSUE #5: Remove `request`
`request` could be removed since this module doesn't need the flexibility for the entire `request` module.

This module still needs to handle streaming the response so I've considered figuring out a way to use `http(s)` directly or something like `superagent`.

### PR DESCRIPTION
**Pull request by Hypnosphi**
Fixes #5 

Unfortunately I wasn't able to verify that those requests still work

### CODE REVIEW

**Comment by doowb** [comment]
Thank you for this!
I see you used `node-fetch` for the streaming part too (instead of `https`), which I agree with. I'm going to merge this in now since the current tests are passing, then I'll get it published (this weekend) after I add a few more tests and do a couple of updates.

Thanks for the contribution 🎉

**Comment by Hypnosphi** [comment]
@doowb can you please release that?

**Comment by silkfire** [comment]
@doowb I agree, could this be released soon?

**Comment by doowb** [comment]
@Hypnosphi sorry for the delay. I'll try to get to this tonight.

**Comment by doowb** [comment]
@Hypnosphi sorry for not getting this published sooner... it's now published as `npm-api@1.0.1`.

**Pull request merged**
